//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureServiceClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectoryEntry", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    [System.SerializableAttribute()]
    public partial class DirectoryEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDirectoryEntry", ReplyAction="http://tempuri.org/IService1/AddDirectoryEntryResponse")]
        AzureServiceClient.ServiceReference1.AddDirectoryEntryResponse AddDirectoryEntry(AzureServiceClient.ServiceReference1.AddDirectoryEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDirectoryEntries", ReplyAction="http://tempuri.org/IService1/GetDirectoryEntriesResponse")]
        AzureServiceClient.ServiceReference1.GetDirectoryEntriesResponse GetDirectoryEntries(AzureServiceClient.ServiceReference1.GetDirectoryEntriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDirectoryEntry", ReplyAction="http://tempuri.org/IService1/GetDirectoryEntryResponse")]
        AzureServiceClient.ServiceReference1.GetDirectoryEntryResponse GetDirectoryEntry(AzureServiceClient.ServiceReference1.GetDirectoryEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveDirectoryEntry", ReplyAction="http://tempuri.org/IService1/RemoveDirectoryEntryResponse")]
        AzureServiceClient.ServiceReference1.RemoveDirectoryEntryResponse RemoveDirectoryEntry(AzureServiceClient.ServiceReference1.RemoveDirectoryEntryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDirectoryEntry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddDirectoryEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AzureServiceClient.ServiceReference1.DirectoryEntry entry;
        
        public AddDirectoryEntryRequest() {
        }
        
        public AddDirectoryEntryRequest(AzureServiceClient.ServiceReference1.DirectoryEntry entry) {
            this.entry = entry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDirectoryEntryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddDirectoryEntryResponse {
        
        public AddDirectoryEntryResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryEntries", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryEntriesRequest {
        
        public GetDirectoryEntriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryEntriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryEntriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AzureServiceClient.ServiceReference1.DirectoryEntry[] GetDirectoryEntriesResult;
        
        public GetDirectoryEntriesResponse() {
        }
        
        public GetDirectoryEntriesResponse(AzureServiceClient.ServiceReference1.DirectoryEntry[] GetDirectoryEntriesResult) {
            this.GetDirectoryEntriesResult = GetDirectoryEntriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryEntry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lastName;
        
        public GetDirectoryEntryRequest() {
        }
        
        public GetDirectoryEntryRequest(string firstName, string lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryEntryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AzureServiceClient.ServiceReference1.DirectoryEntry GetDirectoryEntryResult;
        
        public GetDirectoryEntryResponse() {
        }
        
        public GetDirectoryEntryResponse(AzureServiceClient.ServiceReference1.DirectoryEntry GetDirectoryEntryResult) {
            this.GetDirectoryEntryResult = GetDirectoryEntryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveDirectoryEntry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveDirectoryEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lastName;
        
        public RemoveDirectoryEntryRequest() {
        }
        
        public RemoveDirectoryEntryRequest(string firstName, string lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveDirectoryEntryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveDirectoryEntryResponse {
        
        public RemoveDirectoryEntryResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AzureServiceClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AzureServiceClient.ServiceReference1.IService1>, AzureServiceClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AzureServiceClient.ServiceReference1.AddDirectoryEntryResponse AddDirectoryEntry(AzureServiceClient.ServiceReference1.AddDirectoryEntryRequest request) {
            return base.Channel.AddDirectoryEntry(request);
        }
        
        public AzureServiceClient.ServiceReference1.GetDirectoryEntriesResponse GetDirectoryEntries(AzureServiceClient.ServiceReference1.GetDirectoryEntriesRequest request) {
            return base.Channel.GetDirectoryEntries(request);
        }
        
        public AzureServiceClient.ServiceReference1.GetDirectoryEntryResponse GetDirectoryEntry(AzureServiceClient.ServiceReference1.GetDirectoryEntryRequest request) {
            return base.Channel.GetDirectoryEntry(request);
        }
        
        public AzureServiceClient.ServiceReference1.RemoveDirectoryEntryResponse RemoveDirectoryEntry(AzureServiceClient.ServiceReference1.RemoveDirectoryEntryRequest request) {
            return base.Channel.RemoveDirectoryEntry(request);
        }
    }
}
