//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WCFServiceWebRole1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class testDB1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new testDB1Entities object using the connection string found in the 'testDB1Entities' section of the application configuration file.
        /// </summary>
        public testDB1Entities() : base("name=testDB1Entities", "testDB1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testDB1Entities object.
        /// </summary>
        public testDB1Entities(string connectionString) : base(connectionString, "testDB1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testDB1Entities object.
        /// </summary>
        public testDB1Entities(EntityConnection connection) : base(connection, "testDB1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TestTable_friends> TestTable_friends
        {
            get
            {
                if ((_TestTable_friends == null))
                {
                    _TestTable_friends = base.CreateObjectSet<TestTable_friends>("TestTable_friends");
                }
                return _TestTable_friends;
            }
        }
        private ObjectSet<TestTable_friends> _TestTable_friends;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TestTable_friends EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestTable_friends(TestTable_friends testTable_friends)
        {
            base.AddObject("TestTable_friends", testTable_friends);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testDB1Model", Name="TestTable_friends")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TestTable_friends : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TestTable_friends object.
        /// </summary>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        public static TestTable_friends CreateTestTable_friends(global::System.String lastName, global::System.String firstName)
        {
            TestTable_friends testTable_friends = new TestTable_friends();
            testTable_friends.LastName = lastName;
            testTable_friends.FirstName = firstName;
            return testTable_friends;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                if (_LastName != value)
                {
                    OnLastNameChanging(value);
                    ReportPropertyChanging("LastName");
                    _LastName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LastName");
                    OnLastNameChanged();
                }
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                if (_FirstName != value)
                {
                    OnFirstNameChanging(value);
                    ReportPropertyChanging("FirstName");
                    _FirstName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FirstName");
                    OnFirstNameChanged();
                }
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addr
        {
            get
            {
                return _Addr;
            }
            set
            {
                OnAddrChanging(value);
                ReportPropertyChanging("Addr");
                _Addr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Addr");
                OnAddrChanged();
            }
        }
        private global::System.String _Addr;
        partial void OnAddrChanging(global::System.String value);
        partial void OnAddrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();

        #endregion

    
    }

    #endregion

    
}
